const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const assert = require('node:assert/strict');
const { inspectUpdate, selectTrees, differences, resourceNames } = require('../tools/inspect-update.cjs');
const { root, verifySources } = require('../tools/sources.cjs');
const baseline = verifySources();
const fixture = fs.mkdtempSync(path.join(root, '.validation/update-test-'));
const resources = path.join(fixture, 'resources');
fs.mkdirSync(resources);
const source = (name) => fs.readFileSync(path.join(root, baseline.records.find(r => r.file === `vendor/dnr-${baseline.dnrVersion}/${name}`).file));
fs.writeFileSync(path.join(resources, resourceNames.engine), source('engine.js'));
fs.writeFileSync(path.join(resources, resourceNames.redlines), source('csharp-redlines.json'));
fs.writeFileSync(path.join(resources, resourceNames.trees), zlib.gzipSync(source('cartrees-12.json')));
const installer = path.join(fixture, 'fixture-installer.bin');
fs.writeFileSync(installer, 'test-only; not a real installer');
const args = { resources, installer, version: baseline.dnrVersion, output: path.join(fixture, 'candidate') };
const report = inspectUpdate(args);
assert.equal(report.engineChanged, false);
assert.equal(report.treeDifferences, 0);
assert.equal(report.csharpRedlineDifferences, 0);
assert.equal(report.versionAndSignatureVerifiedByTool, false);
assert.throws(() => inspectUpdate(args), /already exists/);
assert.throws(() => inspectUpdate({ ...args, version: '../escape' }), /release version/);
assert.throws(() => selectTrees({ lengths: { 10: [] } }), /width-12/);
assert.deepEqual(differences({ redline: 6900, old: 1 }, { redline: 7100, added: 2 }).map(d => [d.path, d.kind]),
  [['/redline', 'changed'], ['/old', 'removed'], ['/added', 'added']]);
verifySources();
console.log('Update preparation: unchanged baseline, explicit differences, missing width, unsafe version and overwrite checks passed');
